#user define configuration
biu-net:
  #swagger api configuration
  swagger:
    enable: true
    base-package: site.teamo.biu.net.server.web.controller
  #project configuration
  project:
    version: 1.0.0
    debug: true
  #Tcp port for client connect
  public-server:
    port: 8081
  admin:
    username: admin
    password: ISMvKXpXpadDiUoOSoAfww==

#web server port
server:
  port: 2376

#log configuration
logging:
  level:
    org: info
    site: info

spring:
  #mysql datasource configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biu_net?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:schema.sql
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: select 1

#mybatis configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
#page configuration
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


