biu-net:
  swagger:
    enable: true
  project:
    version: 1.0.0
  public-server:
    port: 8081

logging:
  level:
    org: info
    site: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biu_net?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:schema.sql
    initialization-mode: always
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5           #最小连接数
      maximum-pool-size: 20     #最大连接数
      auto-commit: true         #事务自动提交
      idle-timeout: 600000      #连接超时的最大时长（毫秒），超时则被释放（retired）
      pool-name: DataSourceHikariCP #连接池名称
      max-lifetime: 1800000     #连接生命时长，空闲未被使用超过最大时长则被释放
      connection-test-query: select 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 2376
